---
services:
  frr:
    image: quay.io/frrouting/frr:10.5.1
    container_name: frr
    restart: unless-stopped
    network_mode: host
    cap_add:
      - CAP_NET_RAW
      - NET_ADMIN
      - SYS_ADMIN
    volumes:
      - /opt/frr/config:/etc/frr
